# This is a basic workflow to help you get started with Actions

name: Check Prettier

# Controls when the action will run. Triggers the workflow on pull request
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Install
              run: npm install
              env:
                  CI: true

            - name: Check prettier
              run: npm run check-prettier
